package io.programe.enums;

/**
 *
 * @author lukaz
 */
public enum TipoLogradouro {

    AEROPORTO, ALAMEDA, AREA, AVENIDA, CAMPO, CHÁCARA, COLÔNIA, CONDOMÍNIO,
    CONJUNTO, DISTRITO, ESPLANADA, ESTAÇÃO, ESTRADA, FAVELA, FAZENDA, FEIRA,
    JARDIM, LADEIRA, LAGO, LAGOA, LARGO, LOTEAMENTO, MORRO, NÚCLEO, PARQUE,
    PASSARELA, PÁTIO, PRAÇA, QUADRA, RECANTO, RESIDENCIAL, RODOVIA, RUA, SETOR,
    SÍTIO, TRAVESSA, TRECHO, TREVO, VALE, VEREDA, VIA, VIADUTO, VIELA, VILA

}
